const express = require('express');
const router = express.Router();
const { supabase, isConfigured } = require('../config/db');
const { 
  mockDecks, 
  mockCards, 
  mockReviewLogs, 
  deriveCardStatus, 
  deriveDeckStats 
} = require('../services/deckService');

/**
 * Helper to fetch database or mock data
 */
async function getDecksAndCards() {
  if (isConfigured && supabase) {
    try {
      const { data: decks, error: e1 } = await supabase.from('bo_the_tu_vung').select('*').order('ngay_tao', { ascending: false });
      const { data: cards, error: e2 } = await supabase.from('the_tu_vung').select('*');
      const { data: logs, error: e3 } = await supabase.from('lich_su_on_the').select('*');

      if (!e1 && !e2 && !e3) {
        const finalDecks = (decks && decks.length > 0) ? decks : mockDecks;
        const finalCards = (cards && cards.length > 0) ? cards : mockCards;
        const finalLogs = (logs && logs.length > 0) ? logs : mockReviewLogs;
        return { decks: finalDecks, cards: finalCards, logs: finalLogs, isDb: (decks && decks.length > 0) };
      }
    } catch (err) {
      console.error('Database query fallback to mock:', err);
    }
  }
  return { decks: mockDecks, cards: mockCards, logs: mockReviewLogs, isDb: false };
}

/**
 * 1. GET /api/decks
 * Specs: Screen 01 Deck List
 * Query Params: filter (all|due|mastered), search (string), page (number), limit (number)
 */
router.get('/decks', async (req, res) => {
  try {
    const { filter = 'all', search = '', page = 1, limit = 6 } = req.query;
    const { decks, cards, logs, isDb } = await getDecksAndCards();

    // Map derived stats for each deck
    let processedDecks = decks.map(deck => {
      const stats = deriveDeckStats(deck.id, cards, logs);
      const dateObj = new Date(deck.ngay_tao);
      const formattedDate = `Created ${dateObj.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;

      return {
        id: deck.id,
        userId: deck.nguoi_dung_id || 1,
        title: deck.tieu_de || 'Untitled deck',
        sourcePdfUrl: deck.source_pdf_url,
        isAutoGenerated: deck.is_auto_generated || false,
        createdAt: deck.ngay_tao,
        createdFormatted: formattedDate,
        // Derived fields
        cardCount: stats.total,
        mastery: stats.mastery,
        hasDueCards: stats.hasDueCards,
        isFullyMastered: stats.isFullyMastered,
        stats: {
          total: stats.total,
          mastered: stats.mastered,
          learning: stats.learning,
          new: stats.new,
          accuracy: stats.accuracy
        }
      };
    });

    // Apply Title Search Filter (case-insensitive)
    if (search.trim()) {
      const q = search.trim().toLowerCase();
      processedDecks = processedDecks.filter(d => d.title.toLowerCase().includes(q));
    }

    // Apply Status Filter (all | due | mastered)
    if (filter === 'due') {
      processedDecks = processedDecks.filter(d => d.hasDueCards);
    } else if (filter === 'mastered') {
      processedDecks = processedDecks.filter(d => d.isFullyMastered);
    }

    // Pagination
    const totalItems = processedDecks.length;
    const pageNum = Math.max(1, parseInt(page, 10) || 1);
    const limitNum = Math.max(1, parseInt(limit, 10) || 6);
    const totalPages = Math.ceil(totalItems / limitNum) || 1;
    const startIndex = (pageNum - 1) * limitNum;
    const paginatedDecks = processedDecks.slice(startIndex, startIndex + limitNum);

    res.json({
      success: true,
      source: isDb ? 'database' : 'mock',
      total: totalItems,
      page: pageNum,
      limit: limitNum,
      totalPages,
      data: paginatedDecks
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 2. GET /api/decks/:id
 * Specs: Screen 02 Deck Detail
 */
router.get('/decks/:id', async (req, res) => {
  try {
    const deckId = Number(req.params.id);
    const { decks, cards, logs, isDb } = await getDecksAndCards();

    const deck = decks.find(d => Number(d.id) === deckId);
    if (!deck) {
      return res.status(404).json({ success: false, message: 'Deck not found' });
    }

    const stats = deriveDeckStats(deckId, cards, logs);
    const dateObj = new Date(deck.ngay_tao);
    const formattedDate = `Created ${dateObj.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;

    res.json({
      success: true,
      source: isDb ? 'database' : 'mock',
      data: {
        id: deck.id,
        userId: deck.nguoi_dung_id || 1,
        title: deck.tieu_de || 'Untitled deck',
        sourcePdfUrl: deck.source_pdf_url,
        isAutoGenerated: deck.is_auto_generated || false,
        createdAt: deck.ngay_tao,
        createdFormatted: formattedDate,
        stats: {
          total: stats.total,
          mastered: stats.mastered,
          learning: stats.learning,
          new: stats.new,
          accuracy: stats.accuracy,
          estimatedTimeSeconds: stats.estimatedTimeSeconds,
          masteryPercent: stats.mastery
        }
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 3. POST /api/decks
 * Specs: Create Deck (tieu_de only)
 */
router.post('/decks', async (req, res) => {
  try {
    const { title } = req.body;
    if (!title || !title.trim()) {
      return res.status(400).json({ success: false, message: 'Deck title (tieu_de) is required and cannot be empty' });
    }

    const trimmedTitle = title.trim();

    if (isConfigured && supabase) {
      try {
        const { data, error } = await supabase
          .from('bo_the_tu_vung')
          .insert([{ tieu_de: trimmedTitle, nguoi_dung_id: 1 }])
          .select()
          .single();

        if (!error && data) {
          return res.status(201).json({ success: true, source: 'database', data });
        }
      } catch (err) {
        console.error('Supabase deck creation failed, falling back to mock:', err);
      }
    }

    const newDeck = {
      id: Date.now(),
      nguoi_dung_id: 1,
      tieu_de: trimmedTitle,
      source_pdf_url: null,
      is_auto_generated: false,
      ngay_tao: new Date().toISOString()
    };

    mockDecks.unshift(newDeck);
    res.status(201).json({ success: true, source: 'mock', data: newDeck });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 4. PUT /api/decks/:id
 * Specs: Update Deck Title (tieu_de)
 */
router.put('/decks/:id', async (req, res) => {
  try {
    const deckId = Number(req.params.id);
    const { title } = req.body;

    if (!title || !title.trim()) {
      return res.status(400).json({ success: false, message: 'Deck title cannot be empty' });
    }

    const trimmedTitle = title.trim();

    if (isConfigured && supabase) {
      try {
        const { data, error } = await supabase
          .from('bo_the_tu_vung')
          .update({ tieu_de: trimmedTitle })
          .eq('id', deckId)
          .select()
          .single();

        if (!error && data) {
          return res.json({ success: true, source: 'database', data });
        }
      } catch (err) {
        console.error('Supabase deck update failed:', err);
      }
    }

    const index = mockDecks.findIndex(d => Number(d.id) === deckId);
    if (index === -1) {
      return res.status(404).json({ success: false, message: 'Deck not found' });
    }

    mockDecks[index].tieu_de = trimmedTitle;
    res.json({ success: true, source: 'mock', data: mockDecks[index] });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 5. DELETE /api/decks/:id
 * Specs: Delete Deck & Cascade Cards
 */
router.delete('/decks/:id', async (req, res) => {
  try {
    const deckId = Number(req.params.id);

    if (isConfigured && supabase) {
      try {
        const { error } = await supabase
          .from('bo_the_tu_vung')
          .delete()
          .eq('id', deckId);

        if (!error) {
          return res.json({ success: true, source: 'database', message: 'Deck deleted successfully' });
        }
      } catch (err) {
        console.error('Supabase deck delete failed:', err);
      }
    }

    const initialLength = mockDecks.length;
    const remainingDecks = mockDecks.filter(d => Number(d.id) !== deckId);

    if (remainingDecks.length === initialLength) {
      return res.status(404).json({ success: false, message: 'Deck not found' });
    }

    // Replace array contents
    mockDecks.length = 0;
    mockDecks.push(...remainingDecks);

    res.json({ success: true, source: 'mock', message: 'Deck deleted successfully from mock store' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 6. GET /api/decks/:deckId/cards
 * Specs: Fetch Cards in Deck with Search & Status Filter
 */
router.get('/decks/:deckId/cards', async (req, res) => {
  try {
    const deckId = Number(req.params.deckId);
    const { search = '', status = 'all', page = 1, limit = 10 } = req.query;
    const { cards, logs, isDb } = await getDecksAndCards();

    let deckCards = cards.filter(c => Number(c.bo_the_id) === deckId);

    // Map card with derived status
    let processedCards = deckCards.map(c => {
      const cardStatus = deriveCardStatus(c.id, logs);
      return {
        id: c.id,
        deckId: c.bo_the_id,
        word: c.tu,
        meaning: c.nghia,
        example: c.vi_du || null,
        audioUrl: c.duong_dan_am_thanh || null,
        createdAt: c.ngay_tao,
        status: cardStatus // 'New' | 'Learning' | 'Mastered'
      };
    });

    // Search filter (word or meaning)
    if (search.trim()) {
      const q = search.trim().toLowerCase();
      processedCards = processedCards.filter(c => 
        (c.word && c.word.toLowerCase().includes(q)) || 
        (c.meaning && c.meaning.toLowerCase().includes(q))
      );
    }

    // Status filter
    if (status !== 'all') {
      processedCards = processedCards.filter(c => c.status.toLowerCase() === status.toLowerCase());
    }

    // Pagination
    const totalItems = processedCards.length;
    const pageNum = Math.max(1, parseInt(page, 10) || 1);
    const limitNum = Math.max(1, parseInt(limit, 10) || 10);
    const totalPages = Math.ceil(totalItems / limitNum) || 1;
    const startIndex = (pageNum - 1) * limitNum;
    const paginatedCards = processedCards.slice(startIndex, startIndex + limitNum);

    res.json({
      success: true,
      source: isDb ? 'database' : 'mock',
      total: totalItems,
      page: pageNum,
      limit: limitNum,
      totalPages,
      data: paginatedCards
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 7. POST /api/decks/:deckId/cards
 * Specs: Add Card to Deck (check_the_tu_vung_tu_khong_trang constraint)
 */
router.post('/decks/:deckId/cards', async (req, res) => {
  try {
    const deckId = Number(req.params.deckId);
    const { word, meaning, example, audioUrl } = req.body;

    if (!word || !word.trim()) {
      return res.status(400).json({ success: false, message: 'Flashcard word (tu) is required and cannot be empty' });
    }

    const trimmedWord = word.trim();
    const trimmedMeaning = meaning ? meaning.trim() : '';

    if (isConfigured && supabase) {
      try {
        const { data, error } = await supabase
          .from('the_tu_vung')
          .insert([{ 
            bo_the_id: deckId, 
            tu: trimmedWord, 
            nghia: trimmedMeaning,
            vi_du: example || null,
            duong_dan_am_thanh: audioUrl || null
          }])
          .select()
          .single();

        if (!error && data) {
          return res.status(201).json({ success: true, source: 'database', data });
        }
      } catch (err) {
        console.error('Supabase card creation failed:', err);
      }
    }

    const newCard = {
      id: Date.now(),
      bo_the_id: deckId,
      tu: trimmedWord,
      nghia: trimmedMeaning,
      vi_du: example || null,
      duong_dan_am_thanh: audioUrl || null,
      ngay_tao: new Date().toISOString()
    };

    mockCards.unshift(newCard);
    res.status(201).json({ success: true, source: 'mock', data: newCard });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 8. PUT /api/cards/:cardId
 * Specs: Update Flashcard
 */
router.put('/cards/:cardId', async (req, res) => {
  try {
    const cardId = Number(req.params.cardId);
    const { word, meaning, example, audioUrl } = req.body;

    if (isConfigured && supabase) {
      try {
        const updates = {};
        if (word !== undefined) updates.tu = word.trim();
        if (meaning !== undefined) updates.nghia = meaning.trim();
        if (example !== undefined) updates.vi_du = example;
        if (audioUrl !== undefined) updates.duong_dan_am_thanh = audioUrl;

        const { data, error } = await supabase
          .from('the_tu_vung')
          .update(updates)
          .eq('id', cardId)
          .select()
          .single();

        if (!error && data) {
          return res.json({ success: true, source: 'database', data });
        }
      } catch (err) {
        console.error('Supabase card update failed:', err);
      }
    }

    const index = mockCards.findIndex(c => Number(c.id) === cardId);
    if (index === -1) {
      return res.status(404).json({ success: false, message: 'Flashcard not found' });
    }

    if (word !== undefined) mockCards[index].tu = word.trim();
    if (meaning !== undefined) mockCards[index].nghia = meaning.trim();
    if (example !== undefined) mockCards[index].vi_du = example;
    if (audioUrl !== undefined) mockCards[index].duong_dan_am_thanh = audioUrl;

    res.json({ success: true, source: 'mock', data: mockCards[index] });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 9. DELETE /api/cards/:cardId
 * Specs: Delete Flashcard
 */
router.delete('/cards/:cardId', async (req, res) => {
  try {
    const cardId = Number(req.params.cardId);

    if (isConfigured && supabase) {
      try {
        const { error } = await supabase.from('the_tu_vung').delete().eq('id', cardId);
        if (!error) {
          return res.json({ success: true, source: 'database', message: 'Card deleted successfully' });
        }
      } catch (err) {
        console.error('Supabase card delete failed:', err);
      }
    }

    const initialLength = mockCards.length;
    const remainingCards = mockCards.filter(c => Number(c.id) !== cardId);

    if (remainingCards.length === initialLength) {
      return res.status(404).json({ success: false, message: 'Flashcard not found' });
    }

    mockCards.length = 0;
    mockCards.push(...remainingCards);

    res.json({ success: true, source: 'mock', message: 'Card deleted successfully' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

/**
 * 10. POST /api/review-logs
 * Specs: Record Spaced Repetition (SM-2) Review Log
 */
router.post('/review-logs', async (req, res) => {
  try {
    const { cardId, rating } = req.body; // rating: 'again' | 'hard' | 'good' | 'easy'
    if (!cardId || !rating) {
      return res.status(400).json({ success: false, message: 'cardId and rating are required' });
    }

    const existingLog = mockReviewLogs.find(l => Number(l.flashcard_id) === Number(cardId));
    let easeFactor = existingLog ? Number(existingLog.he_so_do_de) : 2.5;
    let intervalDays = existingLog ? Number(existingLog.khoang_cach_ngay) : 0;
    let wrongCount = existingLog ? Number(existingLog.so_lan_sai) : 0;

    // SM-2 Algorithm Calculation
    if (rating === 'again') {
      intervalDays = 1;
      easeFactor = Math.max(1.3, easeFactor - 0.2);
      wrongCount += 1;
    } else if (rating === 'hard') {
      intervalDays = intervalDays === 0 ? 1 : Math.round(intervalDays * 1.2);
      easeFactor = Math.max(1.3, easeFactor - 0.15);
    } else if (rating === 'good') {
      intervalDays = intervalDays === 0 ? 1 : intervalDays === 1 ? 6 : Math.round(intervalDays * easeFactor);
    } else if (rating === 'easy') {
      intervalDays = intervalDays === 0 ? 4 : Math.round(intervalDays * easeFactor * 1.3);
      easeFactor = Math.min(3.0, easeFactor + 0.15);
    }

    const nextReview = new Date();
    nextReview.setDate(nextReview.getDate() + intervalDays);

    const updatedLog = {
      nguoi_dung_id: 1,
      flashcard_id: Number(cardId),
      he_so_do_de: parseFloat(easeFactor.toFixed(2)),
      khoang_cach_ngay: intervalDays,
      lan_on_tiep_theo: nextReview.toISOString(),
      so_lan_sai: wrongCount
    };

    if (isConfigured && supabase) {
      try {
        const { data, error } = await supabase
          .from('lich_su_on_the')
          .upsert(updatedLog)
          .select()
          .single();

        if (!error && data) {
          return res.status(200).json({ success: true, source: 'database', data });
        }
      } catch (err) {
        console.error('Supabase review log upsert failed:', err);
      }
    }

    const idx = mockReviewLogs.findIndex(l => Number(l.flashcard_id) === Number(cardId));
    if (idx !== -1) {
      mockReviewLogs[idx] = updatedLog;
    } else {
      mockReviewLogs.push(updatedLog);
    }

    res.status(200).json({ success: true, source: 'mock', data: updatedLog });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

module.exports = router;
