-- ============================================================================
-- beepoly — PostgreSQL schema (Supabase-ready)
-- ----------------------------------------------------------------------------
-- Run this entire file in the Supabase SQL Editor (or psql) to (re)create
-- the schema. It is idempotent: it drops and recreates every object it owns.
--
-- This is the runnable source of truth. The dbdiagram.io DBML export is kept
-- separately as beepoly.dbml for visual diagramming.
--
-- Verified against PostgreSQL 18 — see test/ for the constraint test suite.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 0. Reset (idempotent re-runs)
-- ============================================================================
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
ALTER SCHEMA public OWNER TO postgres;

-- Supabase ships anon/authenticated/service_role roles; a plain local
-- PostgreSQL does not. Grant only if they exist so this file runs anywhere.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')) THEN
    EXECUTE 'GRANT ALL ON SCHEMA public TO anon, authenticated, service_role';
  END IF;
END $$;

-- ============================================================================
-- 1. Enums
-- ============================================================================
CREATE TYPE vai_tro_nguoi_dung        AS ENUM ('hoc_vien','phu_huynh','giang_vien','quan_tri_vien');
CREATE TYPE che_do_giao_dien          AS ENUM ('mac_dinh','tre_em','chuyen_nghiep');
CREATE TYPE loai_giong                AS ENUM ('tieng_anh_anh','tieng_anh_my');
CREATE TYPE trinh_do_cefr             AS ENUM ('A1','A2','B1','B2','C1','C2');
CREATE TYPE ky_nang                   AS ENUM ('nghe','noi','doc','viet');
CREATE TYPE loai_noi_dung             AS ENUM ('video','am_thanh','text');
CREATE TYPE loai_ky_thi               AS ENUM ('TOEIC','IELTS');
CREATE TYPE loai_cau_hoi              AS ENUM ('trac_nghiem','dien_vao_cho_trong','noi','viet');
CREATE TYPE nha_cung_cap_dang_nhap    AS ENUM ('google','apple','facebook','email');
CREATE TYPE che_do_ai                 AS ENUM ('tranh_bien','mo_phong_thi','tro_giang');
CREATE TYPE vai_tro_tin_nhan          AS ENUM ('nguoi_dung','tro_ly','he_thong');
CREATE TYPE trang_thai_goi_dang_ky    AS ENUM ('dang_hoat_dong','het_han','da_huy','dung_thu');
CREATE TYPE trang_thai_thanh_toan     AS ENUM ('cho_xu_ly','da_thanh_toan','that_bai','hoan_tien');
CREATE TYPE trang_thai_nguoi_dung     AS ENUM ('dang_hoat_dong','tam_ngung','da_khoa','da_xoa');
CREATE TYPE nha_cung_cap_thanh_toan   AS ENUM ('stripe','paypal','momo','zalopay','vnpay','bank_transfer');

-- ============================================================================
-- 2. Unicode NFC normalisation
-- ----------------------------------------------------------------------------
-- Vietnamese text stored in NFD (decomposed) breaks UNIQUE constraints, "="
-- comparison and ILIKE search — two visually identical strings both insert
-- successfully. The PDF import path (bo_the_tu_vung.source_pdf_url) is a
-- realistic source of NFD data. PostgreSQL has no built-in NFC CHECK, so this
-- normalises on write via trigger. Application code should still call the
-- same normalisation before INSERT/UPDATE.
-- Requires PostgreSQL 13+ (normalize()).
-- ============================================================================
CREATE OR REPLACE FUNCTION fn_normalize_nfc() RETURNS trigger AS $$
DECLARE
  col TEXT;
  val TEXT;
BEGIN
  FOR col IN
    SELECT attname
      FROM pg_attribute
     WHERE attrelid = TG_RELID
       AND attnum > 0
       AND NOT attisdropped
       AND atttypid IN ('text'::regtype, 'varchar'::regtype, 'bpchar'::regtype)
  LOOP
    val := to_jsonb(NEW) ->> col;
    IF val IS NOT NULL THEN
      NEW := jsonb_populate_record(NEW, jsonb_build_object(col, normalize(val, NFC)));
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 3. Tables
-- ============================================================================

CREATE TABLE nguoi_dung (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                   VARCHAR(255) NOT NULL UNIQUE,
  mat_khau_ma_hoa         VARCHAR(255),
  ho_ten                  VARCHAR(150) NOT NULL,
  ngay_sinh               DATE,
  vai_tro                 vai_tro_nguoi_dung      NOT NULL DEFAULT 'hoc_vien',
  che_do_giao_dien        che_do_giao_dien        NOT NULL DEFAULT 'mac_dinh',
  che_do_toi              BOOLEAN                 NOT NULL DEFAULT false,
  co_chu_lon              BOOLEAN                 NOT NULL DEFAULT false,
  giong_tieng_anh_uu_tien loai_giong              NOT NULL DEFAULT 'tieng_anh_my',
  trinh_do_hien_tai       trinh_do_cefr,
  trinh_do_muc_tieu       trinh_do_cefr,
  ma_quoc_gia             CHAR(2),
  trang_thai              trang_thai_nguoi_dung   NOT NULL DEFAULT 'dang_hoat_dong',
  ngay_tao                TIMESTAMPTZ             NOT NULL DEFAULT now(),
  lan_dang_nhap_cuoi      TIMESTAMPTZ,
  -- ISO 3166-1 alpha-2 is always 2 uppercase letters
  CONSTRAINT check_nguoi_dung_ma_quoc_gia
    CHECK (ma_quoc_gia IS NULL OR ma_quoc_gia ~ '^[A-Z]{2}$')
);
CREATE INDEX idx_nguoi_dung_vai_tro     ON nguoi_dung(vai_tro);
CREATE INDEX idx_nguoi_dung_trang_thai  ON nguoi_dung(trang_thai);

CREATE TABLE tai_khoan_dang_nhap (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id               BIGINT NOT NULL,
  nha_cung_cap                nha_cung_cap_dang_nhap NOT NULL,
  ma_tai_khoan_nha_cung_cap   VARCHAR(255) NOT NULL,
  ngay_tao                    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_tai_khoan_dang_nhap_provider_account
  ON tai_khoan_dang_nhap(nha_cung_cap, ma_tai_khoan_nha_cung_cap);
CREATE INDEX idx_tai_khoan_dang_nhap_nguoi_dung_id ON tai_khoan_dang_nhap(nguoi_dung_id);
CREATE UNIQUE INDEX uq_tai_khoan_nguoi_dung_nha_cung_cap
  ON tai_khoan_dang_nhap(nguoi_dung_id, nha_cung_cap);

CREATE TABLE quan_he_gia_dinh (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_phu_huynh              BIGINT NOT NULL,
  id_con                    BIGINT NOT NULL,
  gioi_han_hang_ngay_phut   INTEGER,
  ngay_tao                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT check_quan_he_gia_dinh_gioi_han
    CHECK (gioi_han_hang_ngay_phut IS NULL OR (gioi_han_hang_ngay_phut >= 0 AND gioi_han_hang_ngay_phut <= 1440)),
  -- a user cannot be their own parent
  CONSTRAINT check_quan_he_gia_dinh_khong_tu_tham_chieu
    CHECK (id_phu_huynh <> id_con)
);
CREATE UNIQUE INDEX uq_quan_he_gia_dinh_id_phu_huynh_id_con
  ON quan_he_gia_dinh(id_phu_huynh, id_con);

CREATE TABLE khoa_hoc (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tieu_de         VARCHAR(200) NOT NULL,
  mo_ta           TEXT,
  trinh_do_cefr   trinh_do_cefr NOT NULL,
  la_goi_cao_cap  BOOLEAN NOT NULL DEFAULT false,
  da_xuat_ban     BOOLEAN NOT NULL DEFAULT false,
  nguoi_tao_id    BIGINT,
  ngay_tao        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_khoa_hoc_trinh_do_cefr ON khoa_hoc(trinh_do_cefr);
CREATE INDEX idx_khoa_hoc_nguoi_tao_id  ON khoa_hoc(nguoi_tao_id);
CREATE INDEX idx_khoa_hoc_da_xuat_ban   ON khoa_hoc(da_xuat_ban) WHERE da_xuat_ban;

CREATE TABLE bai_hoc (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  khoa_hoc_id       BIGINT NOT NULL,
  tieu_de           VARCHAR(200) NOT NULL,
  thu_tu            INTEGER NOT NULL,
  ky_nang           ky_nang,
  thoi_luong_phut   INTEGER,
  CONSTRAINT check_bai_hoc_thu_tu        CHECK (thu_tu > 0),
  CONSTRAINT check_bai_hoc_thoi_luong    CHECK (thoi_luong_phut IS NULL OR thoi_luong_phut > 0)
);
CREATE UNIQUE INDEX uq_bai_hoc_khoa_hoc_id_thu_tu ON bai_hoc(khoa_hoc_id, thu_tu);
CREATE INDEX idx_bai_hoc_ky_nang       ON bai_hoc(ky_nang);
CREATE INDEX idx_bai_hoc_khoa_hoc_id   ON bai_hoc(khoa_hoc_id);

CREATE TABLE noi_dung_bai_hoc (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bai_hoc_id          BIGINT NOT NULL,
  loai                loai_noi_dung NOT NULL,
  duong_dan_media     TEXT,
  noi_dung_van_ban    TEXT,
  duong_dan_phu_de    TEXT,
  thu_tu              INTEGER,
  -- video/audio content must carry a media path; block content must carry text
  CONSTRAINT check_noi_dung_bai_hoc_media
    CHECK (loai IN ('video','am_thanh') OR duong_dan_media IS NOT NULL),
  CONSTRAINT check_noi_dung_bai_hoc_text
    CHECK (loai <> 'text' OR noi_dung_van_ban IS NOT NULL),
  CONSTRAINT check_noi_dung_bai_hoc_thu_tu
    CHECK (thu_tu IS NULL OR thu_tu > 0)
);
CREATE INDEX idx_noi_dung_bai_hoc_bai_hoc_id ON noi_dung_bai_hoc(bai_hoc_id);
CREATE UNIQUE INDEX uq_noi_dung_bai_hoc_thu_tu
  ON noi_dung_bai_hoc(bai_hoc_id, thu_tu) WHERE thu_tu IS NOT NULL;

CREATE TABLE dang_ky_khoa_hoc (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id   BIGINT NOT NULL,
  khoa_hoc_id     BIGINT NOT NULL,
  ngay_dang_ky    TIMESTAMPTZ NOT NULL DEFAULT now(),
  ngay_hoan_thanh TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_dang_ky_khoa_hoc_nguoi_dung_id_khoa_hoc_id
  ON dang_ky_khoa_hoc(nguoi_dung_id, khoa_hoc_id);
CREATE INDEX idx_dang_ky_khoa_hoc_khoa_hoc_id ON dang_ky_khoa_hoc(khoa_hoc_id);

CREATE TABLE tien_do_bai_hoc (
  nguoi_dung_id           BIGINT NOT NULL,
  bai_hoc_id              BIGINT NOT NULL,
  phan_tram_hoan_thanh    SMALLINT NOT NULL DEFAULT 0,
  diem_so                 NUMERIC(5,2),
  thoi_gian_hoc_giay      INTEGER NOT NULL DEFAULT 0,
  lan_truy_cap_cuoi       TIMESTAMPTZ,
  CONSTRAINT check_tien_do_bai_hoc_phan_tram
    CHECK (phan_tram_hoan_thanh >= 0 AND phan_tram_hoan_thanh <= 100),
  CONSTRAINT check_tien_do_bai_hoc_thoi_gian
    CHECK (thoi_gian_hoc_giay >= 0),
  CONSTRAINT check_tien_do_bai_hoc_diem_so
    CHECK (diem_so IS NULL OR diem_so >= 0)
);
CREATE INDEX idx_tien_do_bai_hoc_user_id_lesson_id ON tien_do_bai_hoc(nguoi_dung_id, bai_hoc_id);
CREATE INDEX idx_tien_do_bai_hoc_bai_hoc_id        ON tien_do_bai_hoc(bai_hoc_id);

CREATE TABLE chu_de_ngu_phap (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten             VARCHAR(150) NOT NULL,
  trinh_do_cefr   trinh_do_cefr
);
CREATE INDEX idx_chu_de_ngu_phap_trinh_do ON chu_de_ngu_phap(trinh_do_cefr);

CREATE TABLE ky_thi (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loai                        loai_ky_thi NOT NULL,
  tieu_de                     VARCHAR(200) NOT NULL,
  gioi_han_thoi_gian_phut     INTEGER NOT NULL,
  la_goi_cao_cap              BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT check_ky_thi_thoi_gian CHECK (gioi_han_thoi_gian_phut > 0)
);
CREATE INDEX idx_ky_thi_loai            ON ky_thi(loai);
CREATE INDEX idx_ky_thi_la_goi_cao_cap  ON ky_thi(la_goi_cao_cap);

CREATE TABLE phan_thi (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ky_thi_id                   BIGINT NOT NULL,
  ky_nang                     ky_nang NOT NULL,
  thu_tu                      INTEGER,
  gioi_han_thoi_gian_phut     INTEGER,
  CONSTRAINT check_phan_thi_gioi_han
    CHECK (gioi_han_thoi_gian_phut IS NULL OR gioi_han_thoi_gian_phut > 0),
  CONSTRAINT check_phan_thi_thu_tu
    CHECK (thu_tu IS NULL OR thu_tu > 0)
);
CREATE UNIQUE INDEX uq_phan_thi_ky_thi_id_ky_nang ON phan_thi(ky_thi_id, ky_nang);
CREATE INDEX idx_phan_thi_ky_thi_id ON phan_thi(ky_thi_id);

CREATE TABLE cau_hoi (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phan_thi_id         BIGINT NOT NULL,
  chu_de_ngu_phap_id  BIGINT,
  loai                loai_cau_hoi NOT NULL,
  noi_dung            TEXT NOT NULL,
  duong_dan_media     TEXT,
  dap_an_dung         TEXT,
  giai_thich          TEXT,
  diem                NUMERIC(5,2) NOT NULL DEFAULT 1,
  CONSTRAINT check_cau_hoi_diem CHECK (diem > 0)
);
CREATE INDEX idx_cau_hoi_loai               ON cau_hoi(loai);
CREATE INDEX idx_cau_hoi_phan_thi_id        ON cau_hoi(phan_thi_id);
CREATE INDEX idx_cau_hoi_chu_de_ngu_phap_id ON cau_hoi(chu_de_ngu_phap_id);

CREATE TABLE lua_chon_cau_hoi (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cau_hoi_id      BIGINT NOT NULL,
  nhan            CHAR(1),
  noi_dung        TEXT,
  la_dap_an_dung  BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT check_lua_chon_cau_hoi_nhan CHECK (nhan IS NULL OR nhan ~ '^[A-Z]$')
);
CREATE INDEX idx_lua_chon_cau_hoi_cau_hoi_id ON lua_chon_cau_hoi(cau_hoi_id);
CREATE UNIQUE INDEX uq_lua_chon_cau_hoi_cau_hoi_nhan
  ON lua_chon_cau_hoi(cau_hoi_id, nhan) WHERE nhan IS NOT NULL;
-- composite key so cau_tra_loi_lan_thi can bind (lua_chon_id, cau_hoi_id) together
CREATE UNIQUE INDEX uq_lua_chon_cau_hoi_cau_hoi_id ON lua_chon_cau_hoi(cau_hoi_id, id);

CREATE TABLE lan_thi (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id       BIGINT NOT NULL,
  ky_thi_id           BIGINT NOT NULL,
  bat_dau_luc         TIMESTAMPTZ NOT NULL DEFAULT now(),
  ngay_nop            TIMESTAMPTZ,
  total_score         NUMERIC(6,2),
  listening_score     NUMERIC(5,2),
  reading_score       NUMERIC(5,2),
  speaking_score      NUMERIC(4,2),
  writing_score       NUMERIC(4,2),
  CONSTRAINT check_lan_thi_ngay_nop
    CHECK (ngay_nop IS NULL OR ngay_nop >= bat_dau_luc),
  -- TOEIC max 990 (total/listening/reading), IELTS max 9 (speaking/writing)
  CONSTRAINT check_lan_thi_diem CHECK (
    (total_score       IS NULL OR (total_score       >= 0 AND total_score       <= 990)) AND
    (listening_score   IS NULL OR (listening_score   >= 0 AND listening_score   <= 990)) AND
    (reading_score     IS NULL OR (reading_score     >= 0 AND reading_score     <= 990)) AND
    (speaking_score    IS NULL OR (speaking_score    >= 0 AND speaking_score    <= 9))   AND
    (writing_score     IS NULL OR (writing_score     >= 0 AND writing_score     <= 9))
  )
);
CREATE INDEX idx_lan_thi_user_id_started_at ON lan_thi(nguoi_dung_id, bat_dau_luc);
CREATE INDEX idx_lan_thi_ky_thi_id          ON lan_thi(ky_thi_id);

CREATE TABLE cau_tra_loi_lan_thi (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lan_thi_id          BIGINT NOT NULL,
  cau_hoi_id          BIGINT NOT NULL,
  lua_chon_id         BIGINT,
  cau_tra_loi         TEXT,
  duong_dan_am_thanh  TEXT,
  la_dap_an_dung      BOOLEAN NOT NULL DEFAULT false,
  diem_ai             NUMERIC(5,2),
  nhan_xet_ai         TEXT,
  CONSTRAINT check_cau_tra_loi_diem_ai CHECK (diem_ai IS NULL OR diem_ai >= 0)
);
CREATE UNIQUE INDEX uq_cau_tra_loi_lan_thi_lan_thi_id_cau_hoi_id
  ON cau_tra_loi_lan_thi(lan_thi_id, cau_hoi_id);
CREATE INDEX idx_cau_tra_loi_lan_thi_lan_thi_id ON cau_tra_loi_lan_thi(lan_thi_id);
CREATE INDEX idx_cau_tra_loi_lan_thi_cau_hoi_id ON cau_tra_loi_lan_thi(cau_hoi_id);

CREATE TABLE lan_luyen_phat_am (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id       BIGINT NOT NULL,
  bai_hoc_id          BIGINT,
  van_ban_mau         TEXT NOT NULL,
  giong               loai_giong NOT NULL,
  duong_dan_am_thanh  TEXT,
  diem_tuong_dong     NUMERIC(5,2),
  ngay_tao            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT check_lan_luyen_phat_am_diem
    CHECK (diem_tuong_dong IS NULL OR (diem_tuong_dong >= 0 AND diem_tuong_dong <= 100))
);
CREATE INDEX idx_lan_luyen_phat_am_user_id_created_at ON lan_luyen_phat_am(nguoi_dung_id, ngay_tao);
CREATE INDEX idx_lan_luyen_phat_am_bai_hoc_id         ON lan_luyen_phat_am(bai_hoc_id);

CREATE TABLE loi_phat_am (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lan_luyen_phat_am_id    BIGINT NOT NULL,
  tu                      VARCHAR(100),
  am_vi                   TEXT,
  loi_trong_am            BOOLEAN NOT NULL DEFAULT false,
  goi_y                   TEXT
);
CREATE INDEX idx_loi_phat_am_lan_luyen_phat_am_id ON loi_phat_am(lan_luyen_phat_am_id);
CREATE INDEX idx_loi_phat_am_lan_luyen_phat_am_tu ON loi_phat_am(lan_luyen_phat_am_id, tu);

CREATE TABLE cuoc_tro_chuyen_ai (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id       BIGINT NOT NULL,
  che_do              che_do_ai NOT NULL,
  chu_de              VARCHAR(200),
  tu_vung_muc_tieu    JSONB,
  diem_cuoi           NUMERIC(4,2),
  bat_dau_luc         TIMESTAMPTZ NOT NULL DEFAULT now(),
  ket_thuc_luc        TIMESTAMPTZ,
  CONSTRAINT check_cuoc_tro_chuyen_ai_thoi_gian
    CHECK (ket_thuc_luc IS NULL OR ket_thuc_luc >= bat_dau_luc),
  CONSTRAINT check_cuoc_tro_chuyen_ai_diem
    CHECK (diem_cuoi IS NULL OR (diem_cuoi >= 0 AND diem_cuoi <= 100))
);
CREATE INDEX idx_cuoc_tro_chuyen_ai_user_id_started_at ON cuoc_tro_chuyen_ai(nguoi_dung_id, bat_dau_luc);
CREATE INDEX idx_cuoc_tro_chuyen_ai_che_do              ON cuoc_tro_chuyen_ai(che_do);
CREATE INDEX idx_cuoc_tro_chuyen_ai_tu_vung             ON cuoc_tro_chuyen_ai USING GIN (tu_vung_muc_tieu);

CREATE TABLE tin_nhan_ai (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuoc_tro_chuyen_id      BIGINT NOT NULL,
  vai_tro                 vai_tro_tin_nhan NOT NULL,
  noi_dung                TEXT,
  duong_dan_am_thanh      TEXT,
  la_cau_hoi_tiep_theo    BOOLEAN NOT NULL DEFAULT false,
  ngay_tao                TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_tin_nhan_ai_conversation_id_created_at ON tin_nhan_ai(cuoc_tro_chuyen_id, ngay_tao);
CREATE INDEX idx_tin_nhan_ai_vai_tro                    ON tin_nhan_ai(vai_tro);

CREATE TABLE bo_the_tu_vung (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id       BIGINT NOT NULL,
  tieu_de             VARCHAR(200),
  source_pdf_url      TEXT,
  is_auto_generated   BOOLEAN NOT NULL DEFAULT false,
  ngay_tao            TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- auto-generated deck must carry the PDF it came from
  CONSTRAINT check_bo_the_tu_vung_pdf
    CHECK (is_auto_generated = false OR source_pdf_url IS NOT NULL)
);
CREATE INDEX idx_bo_the_tu_vung_nguoi_dung_id ON bo_the_tu_vung(nguoi_dung_id);
CREATE INDEX idx_bo_the_tu_vung_ngay_tao      ON bo_the_tu_vung(nguoi_dung_id, ngay_tao DESC);

CREATE TABLE the_tu_vung (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bo_the_id           BIGINT NOT NULL,
  tu                  VARCHAR(150) NOT NULL,
  nghia               TEXT,
  vi_du               TEXT,
  duong_dan_am_thanh  TEXT,
  CONSTRAINT check_the_tu_vung_tu_khong_trang CHECK (btrim(tu) <> '')
);
CREATE INDEX idx_the_tu_vung_bo_the_id ON the_tu_vung(bo_the_id);
CREATE UNIQUE INDEX uq_the_tu_vung_bo_the_tu ON the_tu_vung(bo_the_id, tu);

CREATE TABLE lich_su_on_the (
  nguoi_dung_id       BIGINT NOT NULL,
  flashcard_id        BIGINT NOT NULL,
  he_so_do_de         NUMERIC(3,2) NOT NULL DEFAULT 2.5,
  khoang_cach_ngay    INTEGER NOT NULL DEFAULT 1,
  lan_on_tiep_theo    TIMESTAMPTZ,
  so_lan_sai          INTEGER NOT NULL DEFAULT 0,
  -- SM-2 ease factor is conventionally 1.30–3.00
  CONSTRAINT check_lich_su_on_the_he_so_do_de CHECK (he_so_do_de >= 1.30 AND he_so_do_de <= 3.00),
  CONSTRAINT check_lich_su_on_the_khoang_cach CHECK (khoang_cach_ngay >= 0),
  CONSTRAINT check_lich_su_on_the_so_lan_sai   CHECK (so_lan_sai >= 0)
);
CREATE INDEX idx_lich_su_on_the_user_id_flashcard_id  ON lich_su_on_the(nguoi_dung_id, flashcard_id);
CREATE INDEX idx_lich_su_on_the_user_id_next_review_at ON lich_su_on_the(nguoi_dung_id, lan_on_tiep_theo);
CREATE INDEX idx_lich_su_on_the_ngay_on               ON lich_su_on_the(lan_on_tiep_theo);

CREATE TABLE diem_yeu_ngu_phap (
  nguoi_dung_id       BIGINT NOT NULL,
  chu_de_ngu_phap_id  BIGINT NOT NULL,
  so_lan_sai          INTEGER NOT NULL DEFAULT 0,
  lan_sai_cuoi        TIMESTAMPTZ,
  CONSTRAINT check_diem_yeu_ngu_phap_so_lan_sai CHECK (so_lan_sai >= 0)
);
CREATE INDEX idx_diem_yeu_ngu_phap_user_id_grammar_topic_id ON diem_yeu_ngu_phap(nguoi_dung_id, chu_de_ngu_phap_id);
CREATE INDEX idx_diem_yeu_ngu_phap_so_lan_sai               ON diem_yeu_ngu_phap(nguoi_dung_id, so_lan_sai);
CREATE INDEX idx_diem_yeu_ngu_phap_chu_de                   ON diem_yeu_ngu_phap(chu_de_ngu_phap_id);

CREATE TABLE lop_hoc (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  giang_vien_id   BIGINT NOT NULL,
  ten             VARCHAR(200) NOT NULL,
  ma_tham_gia     VARCHAR(12) NOT NULL UNIQUE,
  ngay_tao        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT check_lop_hoc_ma_tham_gia CHECK (ma_tham_gia ~ '^[A-Za-z0-9]{6,12}$')
);
CREATE INDEX idx_lop_hoc_giang_vien_id ON lop_hoc(giang_vien_id);

CREATE TABLE thanh_vien_lop (
  lop_hoc_id      BIGINT NOT NULL,
  nguoi_dung_id   BIGINT NOT NULL,
  ngay_tham_gia   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_thanh_vien_lop_class_id_user_id ON thanh_vien_lop(lop_hoc_id, nguoi_dung_id);
CREATE INDEX idx_thanh_vien_lop_nguoi_dung_id    ON thanh_vien_lop(nguoi_dung_id);

CREATE TABLE bai_nop_viet (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id       BIGINT NOT NULL,
  lop_hoc_id          BIGINT,
  noi_dung            TEXT NOT NULL,
  diem_ai             NUMERIC(4,2),
  goi_y_ai            TEXT,
  giang_vien_id       BIGINT,
  diem_cuoi           NUMERIC(4,2),
  nhan_xet_giang_vien TEXT,
  ngay_nop            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT check_bai_nop_viet_diem CHECK (
    (diem_ai   IS NULL OR (diem_ai   >= 0 AND diem_ai   <= 10)) AND
    (diem_cuoi IS NULL OR (diem_cuoi >= 0 AND diem_cuoi <= 10))
  )
);
CREATE INDEX idx_bai_nop_viet_nguoi_dung_id  ON bai_nop_viet(nguoi_dung_id);
CREATE INDEX idx_bai_nop_viet_lop_hoc_id     ON bai_nop_viet(lop_hoc_id);
CREATE INDEX idx_bai_nop_viet_giang_vien_id  ON bai_nop_viet(giang_vien_id);

CREATE TABLE thong_ke_nguoi_dung (
  nguoi_dung_id       BIGINT PRIMARY KEY,
  tong_kinh_nghiem    BIGINT NOT NULL DEFAULT 0,
  chuoi_hoc_hien_tai  INTEGER NOT NULL DEFAULT 0,
  chuoi_hoc_dai_nhat  INTEGER NOT NULL DEFAULT 0,
  ngay_hoc_cuoi       DATE,
  CONSTRAINT check_thong_ke_nguoi_dung
    CHECK (tong_kinh_nghiem >= 0 AND chuoi_hoc_hien_tai >= 0 AND chuoi_hoc_dai_nhat >= 0),
  -- all-time peak streak can never be below the current streak
  CONSTRAINT check_thong_ke_nguoi_dung_chuoi
    CHECK (chuoi_hoc_dai_nhat >= chuoi_hoc_hien_tai)
);

CREATE TABLE goi_dich_vu (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten                 VARCHAR(100) NOT NULL,
  thoi_han_ngay       INTEGER,
  gia                 NUMERIC(12,2) NOT NULL,
  don_vi_tien_te      CHAR(3) NOT NULL DEFAULT 'VND',
  dang_hoat_dong      BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT check_goi_dich_vu_gia      CHECK (gia > 0),
  CONSTRAINT check_goi_dich_vu_thoi_han CHECK (thoi_han_ngay IS NULL OR thoi_han_ngay > 0),
  -- ISO 4217 currency codes are 3 uppercase letters
  CONSTRAINT check_goi_dich_vu_don_vi   CHECK (don_vi_tien_te ~ '^[A-Z]{3}$')
);

CREATE TABLE goi_dang_ky (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id   BIGINT NOT NULL,
  goi_dich_vu_id  BIGINT NOT NULL,
  trang_thai      trang_thai_goi_dang_ky NOT NULL DEFAULT 'dang_hoat_dong',
  bat_dau_luc     TIMESTAMPTZ,
  ket_thuc_luc    TIMESTAMPTZ,
  -- end-before-start subscriptions are invalid
  CONSTRAINT check_goi_dang_ky_thoi_gian
    CHECK (bat_dau_luc IS NULL OR ket_thuc_luc IS NULL OR ket_thuc_luc > bat_dau_luc)
);
CREATE INDEX idx_goi_dang_ky_user_id_status  ON goi_dang_ky(nguoi_dung_id, trang_thai);
CREATE INDEX idx_goi_dang_ky_goi_dich_vu_id  ON goi_dang_ky(goi_dich_vu_id);
-- one row per (user, package, status) — lets a user re-subscribe after expiry/cancel
CREATE UNIQUE INDEX uq_goi_dang_ky_user_package_status
  ON goi_dang_ky(nguoi_dung_id, goi_dich_vu_id, trang_thai);
-- at most ONE active subscription per (user, package)
CREATE UNIQUE INDEX uq_goi_dang_ky_active_per_package
  ON goi_dang_ky(nguoi_dung_id, goi_dich_vu_id)
  WHERE trang_thai = 'dang_hoat_dong';

CREATE TABLE thanh_toan (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id   BIGINT NOT NULL,
  goi_dang_ky_id  BIGINT,
  nha_cung_cap    nha_cung_cap_thanh_toan,
  so_tien         NUMERIC(12,2) NOT NULL,
  don_vi_tien_te  CHAR(3),
  trang_thai      trang_thai_thanh_toan NOT NULL DEFAULT 'cho_xu_ly',
  ma_giao_dich    VARCHAR(120),
  thanh_toan_luc  TIMESTAMPTZ,
  ngay_tao        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT check_thanh_toan_so_tien   CHECK (so_tien > 0),
  -- a payment marked paid must carry a payment timestamp
  CONSTRAINT check_thanh_toan_thoi_diem
    CHECK (trang_thai <> 'da_thanh_toan' OR thanh_toan_luc IS NOT NULL),
  CONSTRAINT check_thanh_toan_don_vi
    CHECK (don_vi_tien_te IS NULL OR don_vi_tien_te ~ '^[A-Z]{3}$')
);
CREATE INDEX idx_thanh_toan_user_id_created_at ON thanh_toan(nguoi_dung_id, ngay_tao);
CREATE UNIQUE INDEX uq_payments_provider_ref
  ON thanh_toan(nha_cung_cap, ma_giao_dich) WHERE ma_giao_dich IS NOT NULL;
CREATE INDEX idx_thanh_toan_trang_thai       ON thanh_toan(trang_thai);
CREATE INDEX idx_thanh_toan_goi_dang_ky_id   ON thanh_toan(goi_dang_ky_id);

CREATE TABLE phien_hoc (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id   BIGINT NOT NULL,
  bat_dau_luc     TIMESTAMPTZ NOT NULL DEFAULT now(),
  ket_thuc_luc    TIMESTAMPTZ,
  duration_sec    INTEGER,
  gio_trong_ngay  SMALLINT,
  CONSTRAINT check_phien_hoc_gio       CHECK (gio_trong_ngay IS NULL OR gio_trong_ngay BETWEEN 0 AND 23),
  CONSTRAINT check_phien_hoc_thoi_gian CHECK (ket_thuc_luc IS NULL OR ket_thuc_luc > bat_dau_luc),
  CONSTRAINT check_phien_hoc_duration  CHECK (duration_sec IS NULL OR duration_sec >= 0)
);
CREATE INDEX idx_phien_hoc_user_id_started_at ON phien_hoc(nguoi_dung_id, bat_dau_luc);

CREATE TABLE diem_ky_nang (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nguoi_dung_id   BIGINT NOT NULL,
  listening       NUMERIC(5,2),
  speaking        NUMERIC(5,2),
  reading         NUMERIC(5,2),
  writing         NUMERIC(5,2),
  ngay_ghi_nhan   DATE NOT NULL,
  CONSTRAINT check_diem_ky_nang CHECK (
    (listening IS NULL OR (listening >= 0 AND listening <= 100)) AND
    (speaking  IS NULL OR (speaking  >= 0 AND speaking  <= 100)) AND
    (reading   IS NULL OR (reading   >= 0 AND reading   <= 100)) AND
    (writing   IS NULL OR (writing   >= 0 AND writing   <= 100))
  )
);
CREATE UNIQUE INDEX uq_diem_ky_nang_nguoi_dung_id_ngay_ghi_nhan
  ON diem_ky_nang(nguoi_dung_id, ngay_ghi_nhan);
CREATE INDEX idx_diem_ky_nang_nguoi_dung_id ON diem_ky_nang(nguoi_dung_id);

-- ============================================================================
-- 4. Triggers
-- ============================================================================

-- A multiple-choice question must have exactly one correct option.
-- A plain CHECK cannot express "count across rows", so this is a deferred
-- constraint trigger (deferrable so a transaction can insert several options
-- before validating).
CREATE OR REPLACE FUNCTION fn_lua_chon_dap_an_dung() RETURNS trigger AS $$
DECLARE
  n INTEGER;
BEGIN
  SELECT count(*) INTO n
    FROM lua_chon_cau_hoi
   WHERE cau_hoi_id = COALESCE(NEW.cau_hoi_id, OLD.cau_hoi_id)
     AND la_dap_an_dung;

  IF n <> 1 THEN
    RAISE EXCEPTION
      'cau_hoi % must have exactly one correct option (found %)',
      COALESCE(NEW.cau_hoi_id, OLD.cau_hoi_id), n;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_lua_chon_dap_an_dung
  AFTER INSERT OR UPDATE OR DELETE ON lua_chon_cau_hoi
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION fn_lua_chon_dap_an_dung();

CREATE TRIGGER trg_nguoi_dung_nfc  BEFORE INSERT OR UPDATE ON nguoi_dung
  FOR EACH ROW EXECUTE FUNCTION fn_normalize_nfc();
CREATE TRIGGER trg_lop_hoc_nfc     BEFORE INSERT OR UPDATE ON lop_hoc
  FOR EACH ROW EXECUTE FUNCTION fn_normalize_nfc();
CREATE TRIGGER trg_goi_dich_vu_nfc BEFORE INSERT OR UPDATE ON goi_dich_vu
  FOR EACH ROW EXECUTE FUNCTION fn_normalize_nfc();

-- ============================================================================
-- 5. Foreign keys
-- ============================================================================

ALTER TABLE tai_khoan_dang_nhap
  ADD CONSTRAINT fk_tai_khoan_dang_nhap_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

ALTER TABLE quan_he_gia_dinh
  ADD CONSTRAINT fk_quan_he_gia_dinh_id_phu_huynh
  FOREIGN KEY (id_phu_huynh) REFERENCES nguoi_dung(id);
ALTER TABLE quan_he_gia_dinh
  ADD CONSTRAINT fk_quan_he_gia_dinh_id_con
  FOREIGN KEY (id_con) REFERENCES nguoi_dung(id);

ALTER TABLE khoa_hoc
  ADD CONSTRAINT fk_khoa_hoc_nguoi_tao_id
  FOREIGN KEY (nguoi_tao_id) REFERENCES nguoi_dung(id);

ALTER TABLE bai_hoc
  ADD CONSTRAINT fk_bai_hoc_khoa_hoc_id
  FOREIGN KEY (khoa_hoc_id) REFERENCES khoa_hoc(id);

ALTER TABLE noi_dung_bai_hoc
  ADD CONSTRAINT fk_noi_dung_bai_hoc_bai_hoc_id
  FOREIGN KEY (bai_hoc_id) REFERENCES bai_hoc(id);

ALTER TABLE dang_ky_khoa_hoc
  ADD CONSTRAINT fk_dang_ky_khoa_hoc_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE dang_ky_khoa_hoc
  ADD CONSTRAINT fk_dang_ky_khoa_hoc_khoa_hoc_id
  FOREIGN KEY (khoa_hoc_id) REFERENCES khoa_hoc(id);

ALTER TABLE tien_do_bai_hoc
  ADD CONSTRAINT fk_tien_do_bai_hoc_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE tien_do_bai_hoc
  ADD CONSTRAINT fk_tien_do_bai_hoc_bai_hoc_id
  FOREIGN KEY (bai_hoc_id) REFERENCES bai_hoc(id);

ALTER TABLE cau_hoi
  ADD CONSTRAINT fk_cau_hoi_chu_de_ngu_phap_id
  FOREIGN KEY (chu_de_ngu_phap_id) REFERENCES chu_de_ngu_phap(id);
ALTER TABLE cau_hoi
  ADD CONSTRAINT fk_cau_hoi_phan_thi_id
  FOREIGN KEY (phan_thi_id) REFERENCES phan_thi(id);

ALTER TABLE phan_thi
  ADD CONSTRAINT fk_phan_thi_ky_thi_id
  FOREIGN KEY (ky_thi_id) REFERENCES ky_thi(id);

ALTER TABLE lua_chon_cau_hoi
  ADD CONSTRAINT fk_lua_chon_cau_hoi_cau_hoi_id
  FOREIGN KEY (cau_hoi_id) REFERENCES cau_hoi(id);

ALTER TABLE lan_thi
  ADD CONSTRAINT fk_lan_thi_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE lan_thi
  ADD CONSTRAINT fk_lan_thi_ky_thi_id
  FOREIGN KEY (ky_thi_id) REFERENCES ky_thi(id);

ALTER TABLE cau_tra_loi_lan_thi
  ADD CONSTRAINT fk_cau_tra_loi_lan_thi_lan_thi_id
  FOREIGN KEY (lan_thi_id) REFERENCES lan_thi(id);
ALTER TABLE cau_tra_loi_lan_thi
  ADD CONSTRAINT fk_cau_tra_loi_lan_thi_cau_hoi_id
  FOREIGN KEY (cau_hoi_id) REFERENCES cau_hoi(id);
-- bind the chosen option to the question being answered — blocks storing an
-- option that belongs to a different question
ALTER TABLE cau_tra_loi_lan_thi
  ADD CONSTRAINT fk_cau_tra_loi_lan_thi_lua_chon_hop_le
  FOREIGN KEY (lua_chon_id, cau_hoi_id)
  REFERENCES lua_chon_cau_hoi(id, cau_hoi_id)
  ON DELETE RESTRICT;

ALTER TABLE lan_luyen_phat_am
  ADD CONSTRAINT fk_lan_luyen_phat_am_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE lan_luyen_phat_am
  ADD CONSTRAINT fk_lan_luyen_phat_am_bai_hoc_id
  FOREIGN KEY (bai_hoc_id) REFERENCES bai_hoc(id);

ALTER TABLE loi_phat_am
  ADD CONSTRAINT fk_loi_phat_am_lan_luyen_phat_am_id
  FOREIGN KEY (lan_luyen_phat_am_id) REFERENCES lan_luyen_phat_am(id);

ALTER TABLE cuoc_tro_chuyen_ai
  ADD CONSTRAINT fk_cuoc_tro_chuyen_ai_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

ALTER TABLE tin_nhan_ai
  ADD CONSTRAINT fk_tin_nhan_ai_cuoc_tro_chuyen_id
  FOREIGN KEY (cuoc_tro_chuyen_id) REFERENCES cuoc_tro_chuyen_ai(id);

ALTER TABLE bo_the_tu_vung
  ADD CONSTRAINT fk_bo_the_tu_vung_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

ALTER TABLE the_tu_vung
  ADD CONSTRAINT fk_the_tu_vung_bo_the_id
  FOREIGN KEY (bo_the_id) REFERENCES bo_the_tu_vung(id);

ALTER TABLE lich_su_on_the
  ADD CONSTRAINT fk_lich_su_on_the_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE lich_su_on_the
  ADD CONSTRAINT fk_lich_su_on_the_flashcard_id
  FOREIGN KEY (flashcard_id) REFERENCES the_tu_vung(id);

ALTER TABLE diem_yeu_ngu_phap
  ADD CONSTRAINT fk_diem_yeu_ngu_phap_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE diem_yeu_ngu_phap
  ADD CONSTRAINT fk_diem_yeu_ngu_phap_chu_de_ngu_phap_id
  FOREIGN KEY (chu_de_ngu_phap_id) REFERENCES chu_de_ngu_phap(id);

ALTER TABLE lop_hoc
  ADD CONSTRAINT fk_lop_hoc_giang_vien_id
  FOREIGN KEY (giang_vien_id) REFERENCES nguoi_dung(id);

ALTER TABLE thanh_vien_lop
  ADD CONSTRAINT fk_thanh_vien_lop_lop_hoc_id
  FOREIGN KEY (lop_hoc_id) REFERENCES lop_hoc(id);
ALTER TABLE thanh_vien_lop
  ADD CONSTRAINT fk_thanh_vien_lop_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

ALTER TABLE bai_nop_viet
  ADD CONSTRAINT fk_bai_nop_viet_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE bai_nop_viet
  ADD CONSTRAINT fk_bai_nop_viet_lop_hoc_id
  FOREIGN KEY (lop_hoc_id) REFERENCES lop_hoc(id);
ALTER TABLE bai_nop_viet
  ADD CONSTRAINT fk_bai_nop_viet_giang_vien_id
  FOREIGN KEY (giang_vien_id) REFERENCES nguoi_dung(id);

ALTER TABLE thong_ke_nguoi_dung
  ADD CONSTRAINT fk_thong_ke_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

ALTER TABLE goi_dang_ky
  ADD CONSTRAINT fk_goi_dang_ky_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE goi_dang_ky
  ADD CONSTRAINT fk_goi_dang_ky_goi_dich_vu_id
  FOREIGN KEY (goi_dich_vu_id) REFERENCES goi_dich_vu(id);

ALTER TABLE thanh_toan
  ADD CONSTRAINT fk_thanh_toan_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);
ALTER TABLE thanh_toan
  ADD CONSTRAINT fk_thanh_toan_goi_dang_ky_id
  FOREIGN KEY (goi_dang_ky_id) REFERENCES goi_dang_ky(id);

ALTER TABLE phien_hoc
  ADD CONSTRAINT fk_phien_hoc_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

ALTER TABLE diem_ky_nang
  ADD CONSTRAINT fk_diem_ky_nang_nguoi_dung_id
  FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id);

COMMIT;
